### ISSUE TITLE
java.lang.NoSuchMethodError: com.yahoo.bullet.pubsub.PubSubMessage.<init> with (ByteArray)PubSubMessageSerDe

### ISSUE THREAD

**Issue by FraBle** [bullet-db/bullet-core#102]
I see the following error when using the latest versions of all tooling with `ByteArrayPubSubMessageSerDe`:

```plain
java.lang.NoSuchMethodError: com.yahoo.bullet.pubsub.PubSubMessage.<init>(Ljava/lang/String;Ljava/io/Serializable;Lcom/yahoo/bullet/pubsub/Metadata;)V
	at com.yahoo.bullet.pubsub.ByteArrayPubSubMessageSerDe$LazyPubSubMessage.<init>(ByteArrayPubSubMessageSerDe.java:34) ~[bullet-core-1.4.1.jar!/:na]
	at com.yahoo.bullet.pubsub.ByteArrayPubSubMessageSerDe$LazyPubSubMessage.<init>(ByteArrayPubSubMessageSerDe.java:30) ~[bullet-core-1.4.1.jar!/:na]
	at com.yahoo.bullet.pubsub.ByteArrayPubSubMessageSerDe.toMessage(ByteArrayPubSubMessageSerDe.java:65) ~[bullet-core-1.4.1.jar!/:na]
```

Component versions:

```
BULLET_UI_VERSION=1.1.0
BULLET_WS_VERSION=1.2.2
BULLET_KAFKA_VERSION=1.2.2
BULLET_SPARK_VERSION=1.0.4
BULLET_EXAMPLES_VERSION=1.0.0
```

`kafka_pubsub_config.yaml`:

```yaml
bullet.pubsub.context.name: "QUERY_SUBMISSION"
bullet.pubsub.class.name: "com.yahoo.bullet.kafka.KafkaPubSub"
bullet.pubsub.kafka.bootstrap.servers: "kafka:29092"
bullet.pubsub.kafka.request.topic.name: "bullet.requests"
bullet.pubsub.kafka.response.topic.name: "bullet.responses"
bullet.pubsub.message.serde.class.name: "com.yahoo.bullet.pubsub.ByteArrayPubSubMessageSerDe"
```

Logs:

```plain

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v1.5.7.RELEASE)

2021-06-29 07:02:02.331  INFO 1 --- [           main] com.yahoo.bullet.rest.Application        : Starting Application v1.2.2 on bullet-web-service-f6884c9bc-nw6zm with PID 1 (/usr/local/var/bullet/service/bullet-service-embedded.jar started by root in /usr/local/var/bullet/service)
2021-06-29 07:02:02.333  INFO 1 --- [           main] com.yahoo.bullet.rest.Application        : No active profile set, falling back to default profiles: default
2021-06-29 07:02:04.333  INFO 1 --- [           main] c.y.bullet.rest.service.SchemaService    : Read 10 fields
2021-06-29 07:02:04.338  INFO 1 --- [           main] c.y.bullet.rest.service.SchemaService    : Schema: {"data":[{"id":"probability","type":"column","attributes":{"description":"Generated from Random#nextDouble","name":"probability","type":"DOUBLE"}},{"id":"gaussian","type":"column","attributes":{"description":"Generated from Random#nextGaussian","name":"gaussian","type":"DOUBLE"}},{"id":"uuid","type":"column","attributes":{"description":"A UUID string generated from UUID#randomUUID","name":"uuid","type":"STRING"}},{"id":"tuple_number","type":"column","attributes":{"description":"A numeric id for the tuple generated in a monotonically increasing fashion in this period","name":"tuple_number","type":"LONG"}},{"id":"duration","type":"column","attributes":{"description":"A random number ranging from 0 to 10050 with a tendency to have a high frequency on lower values","name":"duration","type":"LONG"}},{"id":"type","type":"column","attributes":{"description":"A random string chosen from: foo, bar, baz, qux, quux, norf","name":"type","type":"STRING"}},{"id":"subtypes","type":"column","attributes":{"subFields":[{"name":"field_A","description":"Value randomly chosen from: foo, bar, baz, qux, quux, norf"},{"name":"field_B","description":"Value randomly chosen from: foo, bar, baz, qux, quux, norf"}],"description":"Contains two keys whose values are randomly chosen from: foo, bar, baz, qux, quux, norf","name":"subtypes","type":"STRING_MAP"}},{"id":"tags","type":"column","attributes":{"description":"Contains four keys which are four fragments of the uuid. The values are randomly generated boolean values from Random#nextBoolean","name":"tags","type":"BOOLEAN_MAP"}},{"id":"stats","type":"column","attributes":{"subFields":[{"name":"period_count","description":"The period in which this record was generated"},{"name":"record_number","description":"A monotonically increasing id for the record. There may be gaps in the id but if the data generation has kept up with your maximum tuples per period, this is the nth tuple generated"},{"name":"timestamp","description":"The ms time when this record was generated"},{"name":"nano_time","description":"The ns time when this record was generated"}],"description":"This map contains some numeric information such as the current number of periods etc.","name":"stats","type":"LONG_MAP"}},{"id":"classifiers","type":"column","attributes":{"description":"This contains two maps, each with: field_A and field_B whose values are randomly chosen from: foo, bar, baz, qux, quux, norf","name":"classifiers","type":"STRING_MAP_LIST"}}],"meta":{"version":"1.0"}}
2021-06-29 07:02:04.364  INFO 1 --- [           main] com.yahoo.bullet.common.Config           : Loading configuration file: bullet_defaults.yaml
2021-06-29 07:02:04.369  INFO 1 --- [           main] com.yahoo.bullet.common.Config           : Loading configuration file: storage_defaults.yaml
2021-06-29 07:02:04.391  INFO 1 --- [           main] c.yahoo.bullet.rest.PubSubConfiguration  : Async responder classes are not configured.
2021-06-29 07:02:04.393  INFO 1 --- [           main] com.yahoo.bullet.common.Config           : Loading configuration file: bullet_defaults.yaml
2021-06-29 07:02:04.396  INFO 1 --- [           main] com.yahoo.bullet.common.Config           : Loading configuration file: /bullet/configs/pubsub_config.yaml
2021-06-29 07:02:04.408  INFO 1 --- [           main] com.yahoo.bullet.common.Config           : Loading configuration file: bullet_defaults.yaml
2021-06-29 07:02:04.412  INFO 1 --- [           main] com.yahoo.bullet.common.Config           : Loading configuration file: bullet_kafka_defaults.yaml
2021-06-29 07:02:04.418  INFO 1 --- [           main] com.yahoo.bullet.kafka.KafkaPubSub       : Producer properties:
{retries=5, value.serializer=org.apache.kafka.common.serialization.ByteArraySerializer, request.timeout.ms=3000, acks=all, batch.size=65536, max.block.ms=50000, bootstrap.servers=bullet-pubsub:9092, connections.max.idle.ms=-1, buffer.memory=33554432, key.serializer=org.apache.kafka.common.serialization.StringSerializer, linger.ms=5}
2021-06-29 07:02:04.419  INFO 1 --- [           main] com.yahoo.bullet.kafka.KafkaPubSub       : Consumer properties:
{key.deserializer=org.apache.kafka.common.serialization.StringDeserializer, value.deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer, max.poll.records=50, request.timeout.ms=35000, group.id=bullet-query-consumer, bootstrap.servers=bullet-pubsub:9092, heartbeat.interval.ms=3000, auto.commit.interval.ms=1000, enable.auto.commit=true, fetch.max.wait.ms=500, connections.max.idle.ms=-1, session.timeout.ms=30000, max.poll.interval.ms=30000}
2021-06-29 07:02:04.860  INFO 1 --- [       Thread-2] com.yahoo.bullet.rest.common.Reader      : Reader thread started, ID: 18
2021-06-29 07:02:05.003  INFO 1 --- [           main] com.yahoo.bullet.common.Config           : Loading configuration file: /bullet/configs/query_config.yaml
2021-06-29 07:02:05.004  INFO 1 --- [           main] com.yahoo.bullet.common.Config           : Loading configuration file: bullet_defaults.yaml
2021-06-29 07:02:05.007  INFO 1 --- [           main] com.yahoo.bullet.common.Config           : Loading configuration file: bullet_bql_defaults.yaml
2021-06-29 07:02:05.008  WARN 1 --- [           main] com.yahoo.bullet.common.Validator        : Key: bullet.bql.max.query.length had an invalid value: null. Using default: 2147483647
2021-06-29 07:02:05.015  INFO 1 --- [           main] com.yahoo.bullet.common.Config           : Loading configuration file: bullet_defaults.yaml
2021-06-29 07:02:05.018  INFO 1 --- [           main] com.yahoo.bullet.common.Config           : Loading configuration file: bullet_bql_defaults.yaml
2021-06-29 07:02:05.938  INFO 1 --- [           main] com.yahoo.bullet.rest.Application        : Started Application in 4.004 seconds (JVM running for 4.333)
2021-06-29 07:05:14.611 ERROR 1 --- [nboundChannel-2] .WebSocketAnnotationMethodMessageHandler : Error while processing message GenericMessage [payload=byte[116], headers={simpMessageType=MESSAGE, stompCommand=SEND, nativeHeaders={destination=[/server/request], content-length=[116]}, simpSessionAttributes={}, simpHeartbeat=[J@62ddb425, lookupDestination=/request, simpSessionId=4uo2ppahji1pfq1g4bbsfqw4fppxy034yrfq0hr5uax0gt0ox3q0va5hunfeaq1h, simpDestination=/server/request}]

java.lang.NoSuchMethodError: com.yahoo.bullet.pubsub.PubSubMessage.<init>(Ljava/lang/String;Ljava/io/Serializable;Lcom/yahoo/bullet/pubsub/Metadata;)V
	at com.yahoo.bullet.pubsub.ByteArrayPubSubMessageSerDe$LazyPubSubMessage.<init>(ByteArrayPubSubMessageSerDe.java:34) ~[bullet-core-1.4.1.jar!/:na]
	at com.yahoo.bullet.pubsub.ByteArrayPubSubMessageSerDe$LazyPubSubMessage.<init>(ByteArrayPubSubMessageSerDe.java:30) ~[bullet-core-1.4.1.jar!/:na]
	at com.yahoo.bullet.pubsub.ByteArrayPubSubMessageSerDe.toMessage(ByteArrayPubSubMessageSerDe.java:65) ~[bullet-core-1.4.1.jar!/:na]
	at com.yahoo.bullet.rest.service.QueryService.submit(QueryService.java:74) ~[classes!/:1.2.2]
	at com.yahoo.bullet.rest.service.WebSocketService.submitQuery(WebSocketService.java:87) ~[classes!/:1.2.2]
	at com.yahoo.bullet.rest.controller.WebSocketController.handleNewQuery(WebSocketController.java:89) ~[classes!/:1.2.2]
	at com.yahoo.bullet.rest.controller.WebSocketController.submitWebsocketQuery(WebSocketController.java:65) ~[classes!/:1.2.2]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_292]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_292]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_292]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_292]
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:180) ~[spring-messaging-4.3.11.RELEASE.jar!/:4.3.11.RELEASE]
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:112) ~[spring-messaging-4.3.11.RELEASE.jar!/:4.3.11.RELEASE]
	at org.springframework.messaging.handler.invocation.AbstractMethodMessageHandler.handleMatch(AbstractMethodMessageHandler.java:502) [spring-messaging-4.3.11.RELEASE.jar!/:4.3.11.RELEASE]
	at org.springframework.messaging.simp.annotation.support.SimpAnnotationMethodMessageHandler.handleMatch(SimpAnnotationMethodMessageHandler.java:497) [spring-messaging-4.3.11.RELEASE.jar!/:4.3.11.RELEASE]
	at org.springframework.messaging.simp.annotation.support.SimpAnnotationMethodMessageHandler.handleMatch(SimpAnnotationMethodMessageHandler.java:87) [spring-messaging-4.3.11.RELEASE.jar!/:4.3.11.RELEASE]
	at org.springframework.messaging.handler.invocation.AbstractMethodMessageHandler.handleMessageInternal(AbstractMethodMessageHandler.java:461) [spring-messaging-4.3.11.RELEASE.jar!/:4.3.11.RELEASE]
	at org.springframework.messaging.handler.invocation.AbstractMethodMessageHandler.handleMessage(AbstractMethodMessageHandler.java:399) [spring-messaging-4.3.11.RELEASE.jar!/:4.3.11.RELEASE]
	at org.springframework.messaging.support.ExecutorSubscribableChannel$SendTask.run(ExecutorSubscribableChannel.java:135) [spring-messaging-4.3.11.RELEASE.jar!/:4.3.11.RELEASE]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_292]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_292]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_292]
```

**Comment by FraBle** [comment]
I observe the same error with `PubSubMessageSerDe` as well :( 

```plain

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v1.5.7.RELEASE)

2021-06-29 07:21:18.312  INFO 1 --- [           main] com.yahoo.bullet.rest.Application        : Starting Application v1.2.2 on bullet-web-service-f6884c9bc-5qn25 with PID 1 (/usr/local/var/bullet/service/bullet-service-embedded.jar started by root in /usr/local/var/bullet/service)
2021-06-29 07:21:18.314  INFO 1 --- [           main] com.yahoo.bullet.rest.Application        : No active profile set, falling back to default profiles: default
2021-06-29 07:21:20.159  INFO 1 --- [           main] c.y.bullet.rest.service.SchemaService    : Read 10 fields
2021-06-29 07:21:20.164  INFO 1 --- [           main] c.y.bullet.rest.service.SchemaService    : Schema: {"data":[{"id":"probability","type":"column","attributes":{"description":"Generated from Random#nextDouble","name":"probability","type":"DOUBLE"}},{"id":"gaussian","type":"column","attributes":{"description":"Generated from Random#nextGaussian","name":"gaussian","type":"DOUBLE"}},{"id":"uuid","type":"column","attributes":{"description":"A UUID string generated from UUID#randomUUID","name":"uuid","type":"STRING"}},{"id":"tuple_number","type":"column","attributes":{"description":"A numeric id for the tuple generated in a monotonically increasing fashion in this period","name":"tuple_number","type":"LONG"}},{"id":"duration","type":"column","attributes":{"description":"A random number ranging from 0 to 10050 with a tendency to have a high frequency on lower values","name":"duration","type":"LONG"}},{"id":"type","type":"column","attributes":{"description":"A random string chosen from: foo, bar, baz, qux, quux, norf","name":"type","type":"STRING"}},{"id":"subtypes","type":"column","attributes":{"subFields":[{"name":"field_A","description":"Value randomly chosen from: foo, bar, baz, qux, quux, norf"},{"name":"field_B","description":"Value randomly chosen from: foo, bar, baz, qux, quux, norf"}],"description":"Contains two keys whose values are randomly chosen from: foo, bar, baz, qux, quux, norf","name":"subtypes","type":"STRING_MAP"}},{"id":"tags","type":"column","attributes":{"description":"Contains four keys which are four fragments of the uuid. The values are randomly generated boolean values from Random#nextBoolean","name":"tags","type":"BOOLEAN_MAP"}},{"id":"stats","type":"column","attributes":{"subFields":[{"name":"period_count","description":"The period in which this record was generated"},{"name":"record_number","description":"A monotonically increasing id for the record. There may be gaps in the id but if the data generation has kept up with your maximum tuples per period, this is the nth tuple generated"},{"name":"timestamp","description":"The ms time when this record was generated"},{"name":"nano_time","description":"The ns time when this record was generated"}],"description":"This map contains some numeric information such as the current number of periods etc.","name":"stats","type":"LONG_MAP"}},{"id":"classifiers","type":"column","attributes":{"description":"This contains two maps, each with: field_A and field_B whose values are randomly chosen from: foo, bar, baz, qux, quux, norf","name":"classifiers","type":"STRING_MAP_LIST"}}],"meta":{"version":"1.0"}}
2021-06-29 07:21:20.198  INFO 1 --- [           main] com.yahoo.bullet.common.Config           : Loading configuration file: bullet_defaults.yaml
2021-06-29 07:21:20.203  INFO 1 --- [           main] com.yahoo.bullet.common.Config           : Loading configuration file: storage_defaults.yaml
2021-06-29 07:21:20.234  INFO 1 --- [           main] c.yahoo.bullet.rest.PubSubConfiguration  : Async responder classes are not configured.
2021-06-29 07:21:20.236  INFO 1 --- [           main] com.yahoo.bullet.common.Config           : Loading configuration file: bullet_defaults.yaml
2021-06-29 07:21:20.241  INFO 1 --- [           main] com.yahoo.bullet.common.Config           : Loading configuration file: /bullet/configs/pubsub_config.yaml
2021-06-29 07:21:20.256  INFO 1 --- [           main] com.yahoo.bullet.common.Config           : Loading configuration file: bullet_defaults.yaml
2021-06-29 07:21:20.260  INFO 1 --- [           main] com.yahoo.bullet.common.Config           : Loading configuration file: bullet_kafka_defaults.yaml
2021-06-29 07:21:20.271  INFO 1 --- [           main] com.yahoo.bullet.kafka.KafkaPubSub       : Producer properties:
{retries=5, value.serializer=org.apache.kafka.common.serialization.ByteArraySerializer, request.timeout.ms=3000, acks=all, batch.size=65536, max.block.ms=50000, bootstrap.servers=bullet-pubsub:9092, connections.max.idle.ms=-1, buffer.memory=33554432, key.serializer=org.apache.kafka.common.serialization.StringSerializer, linger.ms=5}
2021-06-29 07:21:20.271  INFO 1 --- [           main] com.yahoo.bullet.kafka.KafkaPubSub       : Consumer properties:
{key.deserializer=org.apache.kafka.common.serialization.StringDeserializer, value.deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer, max.poll.records=50, request.timeout.ms=35000, group.id=bullet-query-consumer, bootstrap.servers=bullet-pubsub:9092, heartbeat.interval.ms=3000, auto.commit.interval.ms=1000, enable.auto.commit=true, fetch.max.wait.ms=500, connections.max.idle.ms=-1, session.timeout.ms=30000, max.poll.interval.ms=30000}
2021-06-29 07:21:21.414  WARN 1 --- [ad | producer-1] org.apache.kafka.clients.NetworkClient   : [Producer clientId=producer-1] Connection to node -1 (bullet-pubsub/10.108.12.116:9092) could not be established. Broker may not be available.
2021-06-29 07:21:21.414  WARN 1 --- [ad | producer-1] org.apache.kafka.clients.NetworkClient   : [Producer clientId=producer-1] Bootstrap broker bullet-pubsub:9092 (id: -1 rack: null) disconnected
2021-06-29 07:21:21.422  WARN 1 --- [ad | producer-2] org.apache.kafka.clients.NetworkClient   : [Producer clientId=producer-2] Connection to node -1 (bullet-pubsub/10.108.12.116:9092) could not be established. Broker may not be available.
2021-06-29 07:21:21.423  WARN 1 --- [ad | producer-2] org.apache.kafka.clients.NetworkClient   : [Producer clientId=producer-2] Bootstrap broker bullet-pubsub:9092 (id: -1 rack: null) disconnected
2021-06-29 07:21:22.532  WARN 1 --- [ad | producer-2] org.apache.kafka.clients.NetworkClient   : [Producer clientId=producer-2] Connection to node -1 (bullet-pubsub/10.108.12.116:9092) could not be established. Broker may not be available.
2021-06-29 07:21:22.532  WARN 1 --- [ad | producer-2] org.apache.kafka.clients.NetworkClient   : [Producer clientId=producer-2] Bootstrap broker bullet-pubsub:9092 (id: -1 rack: null) disconnected
2021-06-29 07:21:23.742  WARN 1 --- [ad | producer-2] org.apache.kafka.clients.NetworkClient   : [Producer clientId=producer-2] Connection to node -1 (bullet-pubsub/10.108.12.116:9092) could not be established. Broker may not be available.
2021-06-29 07:21:23.742  WARN 1 --- [ad | producer-2] org.apache.kafka.clients.NetworkClient   : [Producer clientId=producer-2] Bootstrap broker bullet-pubsub:9092 (id: -1 rack: null) disconnected
2021-06-29 07:21:25.022  WARN 1 --- [ad | producer-2] org.apache.kafka.clients.NetworkClient   : [Producer clientId=producer-2] Connection to node -1 (bullet-pubsub/10.108.12.116:9092) could not be established. Broker may not be available.
2021-06-29 07:21:25.022  WARN 1 --- [ad | producer-2] org.apache.kafka.clients.NetworkClient   : [Producer clientId=producer-2] Bootstrap broker bullet-pubsub:9092 (id: -1 rack: null) disconnected
2021-06-29 07:21:26.452  WARN 1 --- [ad | producer-2] org.apache.kafka.clients.NetworkClient   : [Producer clientId=producer-2] Connection to node -1 (bullet-pubsub/10.108.12.116:9092) could not be established. Broker may not be available.
2021-06-29 07:21:26.452  WARN 1 --- [ad | producer-2] org.apache.kafka.clients.NetworkClient   : [Producer clientId=producer-2] Bootstrap broker bullet-pubsub:9092 (id: -1 rack: null) disconnected
2021-06-29 07:21:28.650  INFO 1 --- [       Thread-2] com.yahoo.bullet.rest.common.Reader      : Reader thread started, ID: 18
2021-06-29 07:21:28.882  INFO 1 --- [           main] com.yahoo.bullet.common.Config           : Loading configuration file: /bullet/configs/query_config.yaml
2021-06-29 07:21:28.883  INFO 1 --- [           main] com.yahoo.bullet.common.Config           : Loading configuration file: bullet_defaults.yaml
2021-06-29 07:21:28.888  INFO 1 --- [           main] com.yahoo.bullet.common.Config           : Loading configuration file: bullet_bql_defaults.yaml
2021-06-29 07:21:28.888  WARN 1 --- [           main] com.yahoo.bullet.common.Validator        : Key: bullet.bql.max.query.length had an invalid value: null. Using default: 2147483647
2021-06-29 07:21:28.896  INFO 1 --- [           main] com.yahoo.bullet.common.Config           : Loading configuration file: bullet_defaults.yaml
2021-06-29 07:21:28.900  INFO 1 --- [           main] com.yahoo.bullet.common.Config           : Loading configuration file: bullet_bql_defaults.yaml
2021-06-29 07:21:30.036  INFO 1 --- [           main] com.yahoo.bullet.rest.Application        : Started Application in 12.17 seconds (JVM running for 12.52)
2021-06-29 07:23:06.315 ERROR 1 --- [nboundChannel-2] .WebSocketAnnotationMethodMessageHandler : Error while processing message GenericMessage [payload=byte[109], headers={simpMessageType=MESSAGE, stompCommand=SEND, nativeHeaders={destination=[/server/request], content-length=[109]}, simpSessionAttributes={}, simpHeartbeat=[J@14e73a19, lookupDestination=/request, simpSessionId=05s5fi0w3auh4rafsnzxvj4wgjm5tw4rvrrzr2iehfwztsjyaem3zjq1rxhiva4q, simpDestination=/server/request}]

java.lang.NoSuchMethodError: com.yahoo.bullet.pubsub.PubSubMessage.<init>(Ljava/lang/String;Ljava/io/Serializable;Lcom/yahoo/bullet/pubsub/Metadata;)V
	at com.yahoo.bullet.pubsub.PubSubMessageSerDe.toMessage(PubSubMessageSerDe.java:47) ~[bullet-core-1.4.1.jar!/:na]
	at com.yahoo.bullet.rest.service.QueryService.submit(QueryService.java:74) ~[classes!/:1.2.2]
	at com.yahoo.bullet.rest.service.WebSocketService.submitQuery(WebSocketService.java:87) ~[classes!/:1.2.2]
	at com.yahoo.bullet.rest.controller.WebSocketController.handleNewQuery(WebSocketController.java:89) ~[classes!/:1.2.2]
	at com.yahoo.bullet.rest.controller.WebSocketController.submitWebsocketQuery(WebSocketController.java:65) ~[classes!/:1.2.2]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_292]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_292]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_292]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_292]
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:180) ~[spring-messaging-4.3.11.RELEASE.jar!/:4.3.11.RELEASE]
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:112) ~[spring-messaging-4.3.11.RELEASE.jar!/:4.3.11.RELEASE]
	at org.springframework.messaging.handler.invocation.AbstractMethodMessageHandler.handleMatch(AbstractMethodMessageHandler.java:502) [spring-messaging-4.3.11.RELEASE.jar!/:4.3.11.RELEASE]
	at org.springframework.messaging.simp.annotation.support.SimpAnnotationMethodMessageHandler.handleMatch(SimpAnnotationMethodMessageHandler.java:497) [spring-messaging-4.3.11.RELEASE.jar!/:4.3.11.RELEASE]
	at org.springframework.messaging.simp.annotation.support.SimpAnnotationMethodMessageHandler.handleMatch(SimpAnnotationMethodMessageHandler.java:87) [spring-messaging-4.3.11.RELEASE.jar!/:4.3.11.RELEASE]
	at org.springframework.messaging.handler.invocation.AbstractMethodMessageHandler.handleMessageInternal(AbstractMethodMessageHandler.java:461) [spring-messaging-4.3.11.RELEASE.jar!/:4.3.11.RELEASE]
	at org.springframework.messaging.handler.invocation.AbstractMethodMessageHandler.handleMessage(AbstractMethodMessageHandler.java:399) [spring-messaging-4.3.11.RELEASE.jar!/:4.3.11.RELEASE]
	at org.springframework.messaging.support.ExecutorSubscribableChannel$SendTask.run(ExecutorSubscribableChannel.java:135) [spring-messaging-4.3.11.RELEASE.jar!/:4.3.11.RELEASE]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_292]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_292]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_292]

```

**Comment by akshaisarma** [comment]
I am taking a look. I have a feeling it's because we haven't released bullet-kafka yet with the latest core so you're not finding the new PubSubMessage constructor.

**Comment by akshaisarma** [comment]
I'd also recommend not moving to a version of bullet-core till you see that all your dependencies (bullet-kafka, bullet-service, bullet-bql, bullet-spark in your case I believe) have been released with a version of that core. In most cases, it should be fine but there can be issues like this sometimes.

**Comment by FraBle** [comment]
> As in bullet-kafka-fat is bringing in an old bullet-core without that constructor.

Yeah, that's what I suspect(ed) as well after checking the release pages on GitHub. For now, I've downgraded bullet-service to 1.1.0 and it is running fine :)

**Comment by akshaisarma** [comment]
Yea I manually tried bullet-kafka with the latest core and bullet-service boots up fine. So can confirm it's kafka fat jar that was the problem. Even if you fixed the service, we still don't have a bullet-spark with the latest core so I'd wait for us to release all of it. We should have that out later this week most likely.

**Comment by FraBle** [comment]
> Even if you fixed the service, we still don't have a bullet-spark with the latest core so I'd wait for us to release all of it. We should have that out later this week most likely.

Yep, makes sense. Thanks for the update! Will keep an eye on the upcoming releases.
